;           Gerber:: Drill Report             
;           =====================             
;    Unit                   : metric
;    Format                 : 2.4, Leading Zeros Suppressed
;    Co-ordinate data Mode  : Absolute Data mode
;+----------------------------------------+
;|  D R I L L   T O O L S   T A B L E     |
;+----------------------------------------+
;|    Drill    |    Tool    |    Drill    |
;|    Tool     |    Size    |    Count    |
;+----------------------------------------+
;|          T01|    0.300000|            5|
;|          T02|    0.457200|            2|
;+----------------------------------------+

M48

METRIC,LZ,00.0000
T01C0.300000
T02C0.457200
%
M71
G90
T01
X00704Y041858
Y079858
X02405Y041858
Y079858
X057558Y065861
T02
X108599Y099701
X108606Y012071

M30
